// Autogenerated by Thrift Compiler (0.13.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"projectThrift/gen-go/user_item"
	"strconv"
	"strings"

	"github.com/apache/thrift/lib/go/thrift"
)

var _ = user_item.GoUnusedProtection__

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  ItemList getItem(i16 pos, i16 count)")
	fmt.Fprintln(os.Stderr, "  TItem deleteItem(i16 id)")
	fmt.Fprintln(os.Stderr, "  TItem addItem(i16 id, TItem item)")
	fmt.Fprintln(os.Stderr, "  TItem editItems(i16 id, TItem item)")
	fmt.Fprintln(os.Stderr, "  TUser addUser(TUser user)")
	fmt.Fprintln(os.Stderr, "  ItemListById getItemByUID(i16 id)")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
	var m map[string]string = h
	return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
	parts := strings.Split(value, ": ")
	if len(parts) != 2 {
		return fmt.Errorf("header should be of format 'Key: Value'")
	}
	h[parts[0]] = parts[1]
	return nil
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	headers := make(httpHeaders)
	var parsedUrl *url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
	flag.Parse()

	if len(urlString) > 0 {
		var err error
		parsedUrl, err = url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}

	cmd := flag.Arg(0)
	var err error
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
		if len(headers) > 0 {
			httptrans := trans.(*thrift.THttpClient)
			for key, value := range headers {
				httptrans.SetHeader(key, value)
			}
		}
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransport(trans)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactory()
		break
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
		break
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
		break
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	iprot := protocolFactory.GetProtocol(trans)
	oprot := protocolFactory.GetProtocol(trans)
	client := user_item.NewItemClient(thrift.NewTStandardClient(iprot, oprot))
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}

	switch cmd {
	case "getItem":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "GetItem requires 2 args")
			flag.Usage()
		}
		tmp0, err21 := (strconv.Atoi(flag.Arg(1)))
		if err21 != nil {
			Usage()
			return
		}
		argvalue0 := int16(tmp0)
		value0 := argvalue0
		tmp1, err22 := (strconv.Atoi(flag.Arg(2)))
		if err22 != nil {
			Usage()
			return
		}
		argvalue1 := int16(tmp1)
		value1 := argvalue1
		fmt.Print(client.GetItem(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "deleteItem":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteItem requires 1 args")
			flag.Usage()
		}
		tmp0, err23 := (strconv.Atoi(flag.Arg(1)))
		if err23 != nil {
			Usage()
			return
		}
		argvalue0 := int16(tmp0)
		value0 := argvalue0
		fmt.Print(client.DeleteItem(context.Background(), value0))
		fmt.Print("\n")
		break
	case "addItem":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "AddItem requires 2 args")
			flag.Usage()
		}
		tmp0, err24 := (strconv.Atoi(flag.Arg(1)))
		if err24 != nil {
			Usage()
			return
		}
		argvalue0 := int16(tmp0)
		value0 := argvalue0
		arg25 := flag.Arg(2)
		mbTrans26 := thrift.NewTMemoryBufferLen(len(arg25))
		defer mbTrans26.Close()
		_, err27 := mbTrans26.WriteString(arg25)
		if err27 != nil {
			Usage()
			return
		}
		factory28 := thrift.NewTJSONProtocolFactory()
		jsProt29 := factory28.GetProtocol(mbTrans26)
		argvalue1 := user_item.NewTItem()
		err30 := argvalue1.Read(jsProt29)
		if err30 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.AddItem(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "editItems":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "EditItems requires 2 args")
			flag.Usage()
		}
		tmp0, err31 := (strconv.Atoi(flag.Arg(1)))
		if err31 != nil {
			Usage()
			return
		}
		argvalue0 := int16(tmp0)
		value0 := argvalue0
		arg32 := flag.Arg(2)
		mbTrans33 := thrift.NewTMemoryBufferLen(len(arg32))
		defer mbTrans33.Close()
		_, err34 := mbTrans33.WriteString(arg32)
		if err34 != nil {
			Usage()
			return
		}
		factory35 := thrift.NewTJSONProtocolFactory()
		jsProt36 := factory35.GetProtocol(mbTrans33)
		argvalue1 := user_item.NewTItem()
		err37 := argvalue1.Read(jsProt36)
		if err37 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.EditItems(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "addUser":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "AddUser requires 1 args")
			flag.Usage()
		}
		arg38 := flag.Arg(1)
		mbTrans39 := thrift.NewTMemoryBufferLen(len(arg38))
		defer mbTrans39.Close()
		_, err40 := mbTrans39.WriteString(arg38)
		if err40 != nil {
			Usage()
			return
		}
		factory41 := thrift.NewTJSONProtocolFactory()
		jsProt42 := factory41.GetProtocol(mbTrans39)
		argvalue0 := user_item.NewTUser()
		err43 := argvalue0.Read(jsProt42)
		if err43 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.AddUser(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getItemByUID":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetItemByUID requires 1 args")
			flag.Usage()
		}
		tmp0, err44 := (strconv.Atoi(flag.Arg(1)))
		if err44 != nil {
			Usage()
			return
		}
		argvalue0 := int16(tmp0)
		value0 := argvalue0
		fmt.Print(client.GetItemByUID(context.Background(), value0))
		fmt.Print("\n")
		break
	case "":
		Usage()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
